name: genji-infra

x-base-settings: &base-settings
  restart: unless-stopped

x-genji-networks: &genji-networks
  networks:
    - genji-network
    - caddy-network

services:
  genji-lust:
    container_name: genji-lust
    image: chillfish8/lust:2.1.0
    command: --config-file "/var/lust/config.yaml"
    <<: [*base-settings, *genji-networks]
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
    volumes:
      - "./lust/config.yaml:/var/lust/config.yaml"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  genji-rabbit:
    container_name: genji-rabbit
    image: rabbitmq:4.0-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    <<: [*base-settings, *genji-networks]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  libretranslate:
    container_name: libretranslate
    build:
      context: ./libretranslate
      dockerfile: Dockerfile
    <<: [*base-settings, *genji-networks]
    mem_limit: 4g
    security_opt:
      - no-new-privileges:true
    environment:
      - LT_DEBUG=true
      - LT_UPDATE_MODELS=true
      - LT_SSL=true
      - LT_SUGGESTIONS=false
      - LT_METRICS=false
      - LT_DISABLE_WEB_UI=true
      - LT_API_KEYS=true
      - LT_THREADS=12
      - LT_FRONTEND_TIMEOUT=2000
      - LT_REQ_LIMIT=0
      # - LT_CHAR_LIMIT=1200
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
    volumes:
      - /home/nebula/bkan0n/appdata/libretranslate/keys:/app/db:rw
      - /home/nebula/bkan0n/appdata/libretranslate/local:/home/libretranslate/.local:rw
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  genji-postgres:
    container_name: genji-postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 25432:5432
    volumes:
      - "/home/nebula/bkan0n/appdata/genji-postgres:/var/lib/postgresql/data"
      - "/home/nebula/bkan0n/backups/genji-postgres:/backups"
      - "/home/nebula/bkan0n/backups/umami:/umami-backups"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    <<: [*base-settings, *genji-networks]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    environment:
      - DATABASE_URL=${DATABASE_URL}/analytics # TODO see if glitch tip can go in this database as well. concat /dbname to the end of secrets?
      - DATABASE_TYPE=postgresql
      - APP_SECRET
    init: true
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    <<: [*base-settings, *genji-networks]
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

networks:
  caddy-network:
    external: true
  genji-network:
    external: true
