x-base-settings: &base-settings
  restart: always

x-genji-networks: &genji-networks
  networks:
    - genji-network
    - caddy-network

services:
  genji-lust:
    container_name: genji-lust
    image: chillfish8/lust:latest
    command: --config-file "/var/lust/config.yaml"
    <<: [*base-settings, *genji-networks]
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
    volumes:
      - "./lust/config.yaml:/var/lust/config.yaml"

  genji-rabbit:
    container_name: genji-rabbit
    image: rabbitmq:4.0-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    <<: [*base-settings, *genji-networks]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  libretranslate:
    container_name: libretranslate
    build:
      context: ./libretranslate
      dockerfile: Dockerfile
    <<: [*base-settings, *genji-networks]
    mem_limit: 4g
    security_opt:
      - no-new-privileges:true
    environment:
      - LT_DEBUG=true
      - LT_UPDATE_MODELS=true
      - LT_SSL=true
      - LT_SUGGESTIONS=false
      - LT_METRICS=false
      - LT_DISABLE_WEB_UI=true
      - LT_API_KEYS=true
      - LT_THREADS=12
      - LT_FRONTEND_TIMEOUT=2000
      - LT_REQ_LIMIT=0
      # - LT_CHAR_LIMIT=1200
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    volumes:
      - /opt/libretranslate/data/keys:/app/db:rw
      - /opt/libretranslate/data/local:/home/libretranslate/.local:rw

  genji-db:
    container_name: genji-postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 9989:5432
    volumes:
      - "/genji-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    <<: [*base-settings, *genji-networks]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  genji-backup:
    image: eeshugerman/postgres-backup-s3:16
    container_name: genji-pg-backup-utility
    environment:
      - SCHEDULE='@daily'     # optional
      - BACKUP_KEEP_DAYS=7     # optional
      - S3_REGION
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - S3_PREFIX
      - S3_ENDPOINT
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    depends_on:
      genji-db:
        condition: service_healthy
    <<: [*base-settings, *genji-networks]








networks:
  caddy-network:
    external: true
  genji-network:
    external: true
