name: Main Deployment

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [init]

jobs:
  deploy:
    uses: bkan0n/bkan0n-deploy-workflow/.github/workflows/main.yml@main
    secrets: inherit
#      SERVER_HOST_IP: ${{ secrets.SERVER_HOST_IP }}
#      SERVER_HOST_USER: ${{ secrets.SERVER_HOST_USER }}
#      SERVER_HOST_SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOST_SSH_PRIVATE_KEY }}
#      SERVER_REPO_LOCATION: ${{ secrets.SERVER_REPO_LOCATION }}
#      REPO_BRANCH: ${{ secrets.REPO_BRANCH }}
#      SERVER_HOST_GITHUB_PAT: ${{ secrets.SERVER_HOST_GITHUB_PAT }}
#      DOPPLER_SERVICE_TOKEN: ${{ secrets.DOPPLER_SERVICE_TOKEN }}
